# Generated by Django 3.2 on 2021-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField()),
                ('spots_in_the_car', models.IntegerField()),
                ('women_only', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
        ),
    ]
