# Generated by Django 3.2 on 2021-05-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
