# Generated by Django 3.2 on 2021-05-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default='male', max_length=6),
        ),
    ]
