# Generated by Django 3.2 on 2021-05-20 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp', '0007_alter_share_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_request_from', to=settings.AUTH_USER_MODEL)),
                ('ride_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_info', to='cp.share')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
