# Generated by Django 3.2 on 2021-05-21 06:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp', '0008_ride_requests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ride_requests',
            unique_together={('from_user', 'to_user', 'ride_data')},
        ),
    ]
