# Generated by Django 3.2 on 2021-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0009_alter_ride_requests_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='ride_requests',
            unique_together=set(),
        ),
    ]
