# Generated by Django 3.2 on 2021-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0013_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='ride_status',
            name='ride_request_mod',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='ride_requests',
            name='ride_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Ride_Status',
        ),
    ]
