# Generated by Django 3.2 on 2021-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0014_auto_20210614_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_requests',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
