# Generated by Django 3.2 on 2021-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0015_ride_requests_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
