# Generated by Django 3.2 on 2021-06-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0016_userprofile_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
