# Generated by Django 3.2 on 2021-06-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0018_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liscence_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liscence_picture',
            field=models.ImageField(blank=True, upload_to='liscence_pics'),
        ),
    ]
