# Generated by Django 3.2 on 2021-06-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0020_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='room_no',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
