# Generated by Django 3.2 on 2021-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0023_alter_share_women_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='women_only',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False),
        ),
    ]
