# Generated by Django 3.2 on 2021-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0024_alter_share_women_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delete_count',
            field=models.IntegerField(default=0),
        ),
    ]
