# Generated by Django 3.2 on 2021-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0027_share_vehicle_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Van', 'Van')], default='Car', max_length=20),
        ),
    ]
