# Generated by Django 3.2 on 2021-06-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0029_auto_20210624_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inter_loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_arr', models.CharField(max_length=10000)),
                ('lat_arr', models.CharField(max_length=10000)),
                ('ride_data_ob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_information', to='cp.share')),
            ],
        ),
    ]
