# Generated by Django 3.2 on 2021-06-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0031_auto_20210627_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inter_loc',
            old_name='lat_long',
            new_name='lat_arr',
        ),
        migrations.AddField(
            model_name='inter_loc',
            name='long_arr',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
