# Generated by Django 3.2 on 2021-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0032_auto_20210628_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
