# Generated by Django 3.2 on 2021-06-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0033_auto_20210630_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, default='@user', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, default='@user', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, default='@user', max_length=50),
        ),
    ]
