# Generated by Django 3.2 on 2021-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0035_share_intermediate_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='pass_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
