# Generated by Django 3.2 on 2021-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0036_share_pass_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='pass_rating',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_lis',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
