# Generated by Django 3.2 on 2021-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0037_auto_20210709_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating_lis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
