# Generated by Django 3.2 on 2021-07-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0038_alter_userprofile_rating_lis'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cp.userprofile'),
        ),
    ]
