# Generated by Django 3.2 on 2021-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0039_share_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
