# Generated by Django 3.2 on 2021-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0040_alter_userprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_requests',
            name='to_locc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
