# Generated by Django 3.2 on 2021-07-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0041_ride_requests_to_locc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride_requests',
            name='to_locc',
        ),
    ]
